In [20]:
#week 1
import numpy as np
n = 2 # number of inputs
num_hidden_layers = 1 # number of hidden layers
m = 2 # number of nodes in each hidden layer
num_nodes_output = 1 # number of nodes in the output layer
weights1 = np.around(np.random.uniform(size=n*m), decimals=2) # initialize the weights
biases1 = np.around(np.random.uniform(size=m), decimals=2) # initialize the biases
print("Weights between Input & Hidden layer",weights1)
print("Bias in Hidden layer",biases1)
weights2 = np.around(np.random.uniform(size=m*num_nodes_output), decimals=2) # initialize the weights
biases2 = np.around(np.random.uniform(size=num_nodes_output), decimals=2) # initialize the biases
print("Weights between Hidden layer & Output",weights2)
print("Bias in Output layer",biases2)

#Output
'''
Weights between Input & Hidden layer [0.42 0.31 0.99 0.45]
Bias in Hidden layer [0.21 0.69]
Weights between Hidden layer & Output [0.13 0.91]
Bias in Output layer [0.38] '''

#week2
import numpy as np
n = 2 # number of inputs
num_hidden_layers = 1 # number of hidden layers
m = 2 # number of nodes in each hidden layer
num_nodes_output = 1 # number of nodes in the output layer
weights = np.around(np.random.uniform(size=6), decimals=2) # initialize the weights
biases = np.around(np.random.uniform(size=6), decimals=2) # initialize the biases
print(weights)
print(biases)
x_0 = 0.5 # input 1
x_1 = 0.85 # input 2
print('x0 is {} and x1 is {}'.format(x_0, x_1))
z_11 = x_0 * weights[0] + x_1 * weights[1] + biases[0]
z_12 = x_0 * weights[2] + x_1 * weights[3] + biases[1]
print('The weighted sum of the inputs at the first node in the hidden layer is {}'.format(np.around(z_11, decimals=2)))
print('The weighted sum of the inputs at the second node in the hidden layer is {}'.format(np.around(z_12, decimals=2)))
a_11 = 1.0 / (1.0 + np.exp(-z_11))
a_12 = 1.0 / (1.0 + np.exp(-z_12))
print('The activation of the first node in the hidden layer is {}'.format(np.around(a_11, 
decimals=2)))
print('The activation of the second node in the hidden layer is {}'.format(np.around(a_12, 
decimals=2)))
z_2 = a_11 * weights[4] + a_12 * weights[5] + biases[2]
print('The weighted sum of the inputs at the node in the output layer is {}'.format(np.around(z_2, decimals=2)))
a_2 = 1.0 / (1.0 + np.exp(-z_2))
print('The output of the network for x1 = 0.5 and x2 = 0.85 is {}'.format(np.around(a_2, decimals=2)))


#Output

'''[0.2 0.16 0.02 1. 0.91 0.26]
[0.36 0.4 0.46 0.88 0.51 0.02]
x0 is 0.5 and x1 is 0.85
The weighted sum of the inputs at the first node in the hidden layer is 0.6
The weighted sum of the inputs at the second node in the hidden layer is 1.26
The activation of the first node in the hidden layer is 0.64
The activation of the second node in the hidden layer is 0.78
The weighted sum of the inputs at the node in the output layer is 1.25
The output of the network for x1 = 0.5 and x2 = 0.85 is 0.78'''

#week 3
import numpy as np # import the Numpy library
num_inputs=5
num_hidden_layers=3
num_nodes_hidden=[3, 2, 3]
num_nodes_output=1
inputs = np.around(np.random.uniform(size=num_inputs), decimals=2)
def initialize_network(num_inputs, num_hidden_layers, num_nodes_hidden, num_nodes_output):
  num_nodes_previous = num_inputs
  network = {}
  for layer in range(num_hidden_layers + 1):
    if layer == num_hidden_layers:
      layer_name = 'output'
      num_nodes = num_nodes_output
    else:
      layer_name = 'layer_{}'.format(layer + 1)
      num_nodes = num_nodes_hidden[layer]
    network[layer_name] = {}
    for node in range(num_nodes):
      node_name = 'node_{}'.format(node+1)
      network[layer_name][node_name] = {'weights': np.around(np.random.uniform(size=num_nodes_previous), decimals=2),'bias': np.around(np.random.uniform(size=1), decimals=2),}
    num_nodes_previous = num_nodes
    return network
small_network = initialize_network(num_inputs, num_hidden_layers, num_nodes_hidden, 
num_nodes_output)
print(small_network)
#output
'''
{'layer_1': {'node_1': {'weights': array([0.41, 0.36, 0.5 , 0.47, 0.67]), 'bias': array([0.37])}, 'node_2': 
{'weights': array([0.8 , 0.59, 0.56, 0.97, 0.98]), 'bias': array([0.44])}, 'node_3': {'weights': 
array([0.07, 0.7 , 0.13, 0.76, 0.14]), 'bias': array([1.])}}, 'layer_2': {'node_1': {'weights': array([0.84, 
0.2 , 0.36]), 'bias': array([0.57])}, 'node_2': {'weights': array([0.71, 0.7 , 0.44]), 'bias': 
array([0.32])}}, 'layer_3': {'node_1': {'weights': array([0.16, 0.58]), 'bias': array([0.5])}, 'node_2': 
{'weights': array([0.2 , 0.43]), 'bias': array([0.79])}, 'node_3': {'weights': array([0.76, 0.24]), 'bias': 
array([0.3])}}, 'output': {'node_1': {'weights': array([0.03, 0.61, 0.6 ]), 'bias': array([0.43])}}}'''


#week4 a
import numpy as np # import the Numpy library
num_inputs=5
num_hidden_layers=3
num_nodes_hidden=[3, 2, 3]
num_nodes_output=1
inputs = np.around(np.random.uniform(size=num_inputs), decimals=2)
def initialize_network(num_inputs, num_hidden_layers, num_nodes_hidden, num_nodes_output):
  num_nodes_previous = num_inputs # number of nodes in the previous layer
  network = {}
  # loop through each layer and randomly initialize the weights and biases associated with each layer
  for layer in range(num_hidden_layers + 1):
    if layer == num_hidden_layers:
      layer_name = 'output' # name last layer in the network output
      num_nodes = num_nodes_output
    else:
      layer_name = 'layer_{}'.format(layer + 1) # otherwise give the layer a number
      num_nodes = num_nodes_hidden[layer]
 
# initialize weights and bias for each node
      network[layer_name] = {}
      for node in range(num_nodes):
        node_name = 'node_{}'.format(node+1)
        network[layer_name][node_name] = {'weights': np.around(np.random.uniform(size=num_nodes_previous), decimals=2),'bias': np.around(np.random.uniform(size=1), decimals=2),}
      num_nodes_previous = num_nodes
  return network # return the network
def compute_weighted_sum(inputs, weights, bias):
 return np.sum(inputs * weights) + bias
def node_activation(weighted_sum):
  return 1.0 / (1.0 + np.exp(-1 * weighted_sum))
small_network = initialize_network(num_inputs, num_hidden_layers, num_nodes_hidden, 
num_nodes_output)
print('The inputs to the network are {}'.format(inputs))
node_weights = small_network['layer_1']['node_1']['weights']
node_bias = small_network['layer_1']['node_1']['bias']
weighted_sum = compute_weighted_sum(inputs, node_weights, node_bias)
node_output = node_activation(compute_weighted_sum(inputs, node_weights, node_bias))
def forward_propagate(network, inputs):
  layer_inputs = list(inputs) # start with the input layer as the input to the first hidden layer
  for layer in network:
    layer_data = network[layer]
    layer_outputs = []
    for layer_node in layer_data:
      node_data = layer_data[layer_node]
 
 # compute the weighted sum and the output of each node at the same time
      node_output = node_activation(compute_weighted_sum(layer_inputs, node_data['weights'], node_data['bias']))
      layer_outputs.append(np.around(node_output[0], decimals=2))
    if layer != 'output':
      print('The outputs of the nodes in hidden layer number {} is {}'.format(layer.split('_')[1], layer_outputs))
    layer_inputs = layer_outputs # set the output of this layer to be the input to next layer
  network_predictions = layer_outputs
  return network_predictions
predictions = forward_propagate(small_network, inputs)
print('The predicted value by the network for the given input is {}'.format(np.around(predictions, 
decimals=2)))
#output
'''
The inputs to the network are [0.76 0.63 0.96 0.01 0.22]
The outputs of the nodes in hidden layer number 1 is [0.71, 0.77, 0.91]
The outputs of the nodes in hidden layer number 2 is [0.81, 0.75]
The outputs of the nodes in hidden layer number 3 is [0.82, 0.73, 0.8]
The predicted value by the network for the given input is [0.82 0.73 0.8 ]'''
 
#week4b

import numpy as np # import the Numpy library
num_inputs=5
num_hidden_layers=3
num_nodes_hidden=[3, 2, 3]
num_nodes_output=1
inputs = np.around(np.random.uniform(size=num_inputs), decimals=2)
def initialize_network(num_inputs, num_hidden_layers, num_nodes_hidden, num_nodes_output):
  num_nodes_previous = num_inputs # number of nodes in the previous layer
  network = {}
 
 # loop through each layer and randomly initialize the weights and biases associated with each layer
  for layer in range(num_hidden_layers + 1):
    if layer == num_hidden_layers:
      layer_name = 'output' # name last layer in the network output
      num_nodes = num_nodes_output
    else:
      layer_name = 'layer_{}'.format(layer + 1) # otherwise give the layer a number
      num_nodes = num_nodes_hidden[layer]
 
 # initialize weights and bias for each node
    network[layer_name] = {}
    for node in range(num_nodes):
      node_name = 'node_{}'.format(node+1)
      network[layer_name][node_name] = {'weights': np.around(np.random.uniform(size=num_nodes_previous), decimals=2),'bias': np.around(np.random.uniform(size=1), decimals=2),}
 
    num_nodes_previous = num_nodes
  return network # return the network
small_network = initialize_network(num_inputs, num_hidden_layers, num_nodes_hidden, num_nodes_output)

def compute_weighted_sum(inputs, weights, bias):
  return np.sum(inputs * weights) + bias
def node_activation(weighted_sum):
  return (np.exp(weighted_sum)-np.exp(-1 * weighted_sum)) / (np.exp(weighted_sum)+np.exp(-1 * weighted_sum))
print('The inputs to the network are {}'.format(inputs))
node_weights = small_network['layer_1']['node_1']['weights']
node_bias = small_network['layer_1']['node_1']['bias']
weighted_sum = compute_weighted_sum(inputs, node_weights, node_bias)
node_output = node_activation(compute_weighted_sum(inputs, node_weights, node_bias))
def forward_propagate(network, inputs):
  layer_inputs = list(inputs) # start with the input layer as the input to the first hidden layer
  for layer in network:
    layer_data = network[layer]
    layer_outputs = []
    for layer_node in layer_data:
      node_data = layer_data[layer_node]
 
 # compute the weighted sum and the output of each node at the same time
      node_output = node_activation(compute_weighted_sum(layer_inputs, node_data['weights'], node_data['bias']))
      layer_outputs.append(np.around(node_output[0], decimals=2))
 
    if layer != 'output':
      print('The outputs of the nodes in hidden layer number {} is {}'.format(layer.split('_')[1], layer_outputs))
    layer_inputs = layer_outputs # set the output of this layer to be the input to next layer
    network_predictions = layer_outputs
  return network_predictions
predictions = forward_propagate(small_network, inputs)
print('The predicted value by the network for the given input is {}'.format(np.around(predictions, 
decimals=2)))
#output
'''The inputs to the network are [0.55 0.13 0.85 0.92 0.11]
The outputs of the nodes in hidden layer number 1 is [0.92, 0.99, 0.98]
The outputs of the nodes in hidden layer number 2 is [0.96, 0.92]
The outputs of the nodes in hidden layer number 3 is [0.86, 0.98, 0.9]
The predicted value by the network for the given input is [0.7]'''

 #week5

import numpy as np
num_inputs=5
num_hidden_layers=3
num_nodes_hidden=[3, 2, 3]
num_nodes_output=1
inputs = np.around(np.random.uniform(size=num_inputs), decimals=2)

def initialize_network(num_inputs, num_hidden_layers, num_nodes_hidden, num_nodes_output):
  num_nodes_previous = num_inputs # number of nodes in the previous layer
  network = {}
 
 # loop through each layer and randomly initialize the weights and biases associated with each layer
  for layer in range(num_hidden_layers + 1):
    if layer == num_hidden_layers:
      layer_name = 'output' # name last layer in the network output
      num_nodes = num_nodes_output
    else:
      layer_name = 'layer_{}'.format(layer + 1) # otherwise give the layer a number
      num_nodes = num_nodes_hidden[layer]
 
 # initialize weights and bias for each node
    network[layer_name] = {}
    for node in range(num_nodes):
      node_name = 'node_{}'.format(node+1)
      network[layer_name][node_name] = {'weights': np.around(np.random.uniform(size=num_nodes_previous), decimals=2),'bias': np.around(np.random.uniform(size=1), decimals=2),}
 
    num_nodes_previous = num_nodes
  return network # return the network
small_network = initialize_network(num_inputs, num_hidden_layers, num_nodes_hidden, num_nodes_output)
def compute_weighted_sum(inputs, weights, bias):
  return np.sum(inputs * weights) + bias
def node_activation(weighted_sum):
  return (np.maximum(0,weighted_sum))
print('The inputs to the network are {}'.format(inputs))
node_weights = small_network['layer_1']['node_1']['weights']
node_bias = small_network['layer_1']['node_1']['bias']
weighted_sum = compute_weighted_sum(inputs, node_weights, node_bias)
node_output = node_activation(compute_weighted_sum(inputs, node_weights, node_bias))
def forward_propagate(network, inputs):
  layer_inputs = list(inputs) # start with the input layer as the input to the first hidden layer
  for layer in network:
    layer_data = network[layer]
    layer_outputs = []
    for layer_node in layer_data:
      node_data = layer_data[layer_node]
 
 # compute the weighted sum and the output of each node at the same time
      node_output = node_activation(compute_weighted_sum(layer_inputs, node_data['weights'], node_data['bias']))
      layer_outputs.append(np.around(node_output[0], decimals=2))
    if layer != 'output':
      print('The outputs of the nodes in hidden layer number {} is {}'.format(layer.split('_')[1], layer_outputs))
 
    layer_inputs = layer_outputs # set the output of this layer to be the input to next layer
  network_predictions = layer_outputs
  return network_predictions
predictions = forward_propagate(small_network, inputs)
print('The predicted value by the network for the given input is {}'.format(np.around(predictions, 
decimals=2)))

#output
'''The inputs to the network are [0.64 0.9  0.99 0.34 0.61]
The outputs of the nodes in hidden layer number 1 is [3.0, 2.05, 3.11]
The outputs of the nodes in hidden layer number 2 is [5.04, 5.19]
The outputs of the nodes in hidden layer number 3 is [5.27, 6.29, 1.91]
The predicted value by the network for the given input is [8.22] '''

{'layer_1': {'node_1': {'weights': array([0.3 , 0.47, 0.95, 0.06, 0.9 ]), 'bias': array([0.46])}, 'node_2': {'weights': array([0.62, 0.88, 0.04, 0.69, 0.22]), 'bias': array([0.1])}, 'node_3': {'weights': array([0.39, 0.5 , 0.59, 0.96, 0.5 ]), 'bias': array([0.15])}}}


"\nimport numpy as np\nnum_inputs=5\nnum_hidden_layers=3\nnum_nodes_hidden=[3, 2, 3]\nnum_nodes_output=1\ninputs = np.around(np.random.uniform(size=num_inputs), decimals=2)\n\ndef initialize_network(num_inputs, num_hidden_layers, num_nodes_hidden, num_nodes_output):\n  num_nodes_previous = num_inputs # number of nodes in the previous layer\n  network = {}\n \n # loop through each layer and randomly initialize the weights and biases associated with each layer\n  for layer in range(num_hidden_layers + 1):\n    if layer == num_hidden_layers:\n      layer_name = 'output' # name last layer in the network output\n      num_nodes = num_nodes_output\n    else:\n      layer_name = 'layer_{}'.format(layer + 1) # otherwise give the layer a number\n      num_nodes = num_nodes_hidden[layer]\n \n # initialize weights and bias for each node\n    network[layer_name] = {}\n    for node in range(num_nodes):\n      node_name = 'node_{}'.format(node+1)\n      network[layer_name][node_name] = {'weights': n